# Generated by Django 2.1 on 2018-11-05 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=200)),
                ('direccion_paciente', models.CharField(max_length=200)),
                ('telefono_paciente', models.CharField(max_length=200)),
                ('correo_paciente', models.EmailField(max_length=200)),
                ('sintomas_paciente', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
