# Generated by Django 2.1 on 2018-11-06 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181105_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doctor', models.CharField(max_length=200)),
                ('direccion_doctor', models.CharField(max_length=200)),
                ('telefono_doctor', models.CharField(max_length=200)),
                ('correo_doctor', models.EmailField(max_length=200)),
                ('colegiado_doctor', models.CharField(max_length=200)),
                ('especialidad_doctor', models.CharField(max_length=200)),
                ('fecha_creacion2', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion2', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
